spring:
  application:
    name: gateway
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Hapus kata 'app:' yang sebelumnya ada di atas ini
jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
